swagger: "2.0"
info:
  title: Add Department
  description: Adiciona um novo departamento
  version: "1.0"
paths:
  /departments:
    post:
      summary: Adicionar um departamento
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: "Engineering"
      responses:
        201:
          description: Departamento adicionado com sucesso
        400:
          description: Erro na requisição
